--- @class CharacterModel
--- @field health number Текущее здоровье персонажа (по умолчанию 100)
--- @field speed number Скорость перемещения персонажа (по умолчанию 50)
--- @field position vector3 Позиция персонажа в 3D пространстве (по умолчанию 0,0,0)
--- @field components table<string, any> Таблица компонентов персонажа
--- @field controller_url hash URL контроллера персонажа
--- @field is_moving boolean Если движимся

--- @class CharacterModelData
--- @field health number Текущее здоровье персонажа (по умолчанию 100)
--- @field speed number Скорость перемещения персонажа (по умолчанию 50)
--- @field position vector3 Позиция персонажа в 3D пространстве (по умолчанию 0,0,0)
--- @field controller_url hash URL контроллера персонажа
